export interface Product {
  id: string
  name: string
  price: number
  originalPrice?: number
  image: string
  rating: number
  reviews: number
  category: string
  description: string
  tags: string[]
  stock: number
  isBestSeller?: boolean
  isNew?: boolean
  isLowStock?: boolean
}

export const categories = [
  { id: 'cat-food', name: 'Cat Food', icon: '🐱' },
  { id: 'dog-food', name: 'Dog Food', icon: '🐶' },
  { id: 'cat-toys', name: 'Cat Toys', icon: '🎾' },
  { id: 'cat-litter', name: 'Cat Litter', icon: '🧽' },
  { id: 'toys-treats', name: 'Toys & Treats', icon: '🎾' },
  { id: 'grooming', name: 'Grooming', icon: '🧴' },
  { id: 'health-care', name: 'Health Care', icon: '💊' },
  { id: 'accessories', name: 'Accessories', icon: '🎀' },
  { id: 'reflex', name: 'Reflex Brand', icon: '⭐' },
]

// Mock data - MongoDB-ready structure
export const productsData: Record<string, Product[]> = {
  'cat-food': [
    {
      id: 'cf001',
      name: 'Royal Canin Adult Cat Food',
      price: 1850,
      originalPrice: 2100,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 124,
      category: 'cat-food',
      description: 'Premium dry cat food for adult cats with balanced nutrition. Royal Canin brand quality with 2kg weight.',
      tags: ['Premium', 'Adult', 'Royal Canin', '2kg'],
      stock: 45,
      isBestSeller: true,
    },
    {
      id: 'cf002',
      name: 'Whiskas Cat Pouches Variety Pack',
      price: 450,
      originalPrice: 520,
      image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 89,
      category: 'cat-food',
      description: 'Convenient variety pack of cat pouches with different flavors. Contains 12 pouches.',
      tags: ['Pouches', 'Variety', 'Whiskas', '12 pouches'],
      stock: 78,
    },
    {
      id: 'cf003',
      name: 'Hills Science Diet Kitten Food',
      price: 2200,
      originalPrice: 2500,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 156,
      category: 'cat-food',
      description: 'Specially formulated nutrition for growing kittens. Hills Science Diet quality with 1.5kg weight.',
      tags: ['Kitten', 'Science Diet', 'Hills', '1.5kg'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'cf004',
      name: 'Felix As Good As It Looks',
      price: 320,
      originalPrice: 380,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.4,
      reviews: 67,
      category: 'cat-food',
      description: 'Delicious wet food with meat chunks in jelly. Felix brand quality with 400g weight.',
      tags: ['Wet Food', 'Felix', '400g'],
      stock: 0,
      isLowStock: true,
    },
    {
      id: 'cf005',
      name: 'Me-O Cat Treats Tuna',
      price: 180,
      originalPrice: 220,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 43,
      category: 'cat-food',
      description: 'Delicious tuna flavored treats for cats. Me-O brand quality with 150g weight.',
      tags: ['Treats', 'Tuna', 'Me-O', '150g'],
      stock: 67,
    },
    {
      id: 'cf006',
      name: 'Purina Pro Plan Premium Dry',
      price: 3200,
      originalPrice: 3600,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 92,
      category: 'cat-food',
      description: 'Premium dry cat food for optimal nutrition. Purina Pro Plan quality with 3kg weight.',
      tags: ['Premium', 'Dry Food', 'Purina', '3kg'],
      stock: 34,
    },
  ],
  'dog-food': [
    {
      id: 'df001',
      name: 'Royal Canin Medium Adult Dog Food',
      price: 2250,
      originalPrice: 2600,
      image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 167,
      category: 'dog-food',
      description: 'Complete nutrition for medium breed adult dogs. Royal Canin brand quality with 3kg weight.',
      tags: ['Adult', 'Medium Breed', 'Royal Canin', '3kg'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'df002',
      name: 'Pedigree Puppy Dry Food Chicken',
      price: 850,
      originalPrice: 1000,
      image: 'https://images.unsplash.com/photo-1552053628-0dcb5a60e3de?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 89,
      category: 'dog-food',
      description: 'Chicken flavored dry food specially formulated for puppies. Pedigree brand quality with 1.2kg weight.',
      tags: ['Puppy', 'Chicken', 'Pedigree', '1.2kg'],
      stock: 34,
    },
    {
      id: 'df003',
      name: 'Hills Science Diet Puppy Food',
      price: 1850,
      originalPrice: 2100,
      image: 'https://images.unsplash.com/photo-1587402092301-725e37c70fd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 134,
      category: 'dog-food',
      description: 'Science-based nutrition for growing puppies. Hills Science Diet quality with 1.5kg weight.',
      tags: ['Puppy', 'Science Diet', 'Hills', '1.5kg'],
      stock: 12,
      isNew: true,
    },
    {
      id: 'df004',
      name: 'Cesar Adult Dog Treats',
      price: 420,
      originalPrice: 480,
      image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 76,
      category: 'dog-food',
      description: 'Delicious treats for adult dogs. Cesar brand quality with 300g weight.',
      tags: ['Treats', 'Adult', 'Cesar', '300g'],
      stock: 0,
      isLowStock: true,
    },
    {
      id: 'df005',
      name: 'Nutro Max Adult Dry Food',
      price: 3200,
      originalPrice: 3600,
      image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 112,
      category: 'dog-food',
      description: 'Premium dry food for adult dogs. Nutro Max quality with 5kg weight.',
      tags: ['Adult', 'Dry Food', 'Nutro', '5kg'],
      stock: 23,
    },
    {
      id: 'df006',
      name: 'Cosequin Dog Joint Health',
      price: 1850,
      originalPrice: 2200,
      image: 'https://images.unsplash.com/photo-1587402092301-725e37c70fd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 58,
      category: 'dog-food',
      description: 'Joint health supplement for dogs. Cosequin brand quality with 60 tablets.',
      tags: ['Supplement', 'Joint Health', 'Cosequin', '60 tablets'],
      stock: 45,
    },
  ],
  'toys-treats': [
    {
      id: 'tt001',
      name: 'Interactive Cat Wand Toy',
      price: 450,
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 156,
      category: 'toys-treats',
      description: 'Fun interactive wand toy to keep cats active and engaged.',
      tags: ['Interactive', 'Cat'],
      stock: 89,
      isBestSeller: true,
    },
    {
      id: 'tt002',
      name: 'Kong Classic Dog Toy',
      price: 850,
      image: 'https://images.unsplash.com/photo-1605043204319-d14e5ba4719e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 234,
      category: 'toys-treats',
      description: 'Durable rubber toy perfect for stuffing with treats.',
      tags: ['Durable', 'Dog'],
      stock: 67,
    },
    {
      id: 'tt003',
      name: 'Catnip Mice Toys (Pack of 6)',
      price: 320,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 189,
      category: 'toys-treats',
      description: 'Soft mice toys filled with premium catnip.',
      tags: ['Catnip', 'Pack'],
      stock: 45,
      isNew: true,
    },
    {
      id: 'tt004',
      name: 'Dog Training Treats',
      price: 650,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 145,
      category: 'toys-treats',
      description: 'High-value treats perfect for training sessions.',
      tags: ['Training', 'Treats'],
      stock: 7,
      isLowStock: true,
    },
  ],
  'grooming': [
    {
      id: 'gr001',
      name: 'Professional Pet Grooming Kit',
      price: 2800,
      originalPrice: 3200,
      image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 98,
      category: 'grooming',
      description: 'Complete grooming kit with brushes, clippers, and accessories.',
      tags: ['Professional', 'Complete Kit'],
      stock: 23,
      isBestSeller: true,
    },
    {
      id: 'gr002',
      name: 'Pet Shampoo & Conditioner Set',
      price: 950,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 167,
      category: 'grooming',
      description: 'Gentle shampoo and conditioner for sensitive pet skin.',
      tags: ['Gentle', 'Set'],
      stock: 54,
    },
    {
      id: 'gr003',
      name: 'Nail Clippers for Dogs & Cats',
      price: 450,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 234,
      category: 'grooming',
      description: 'Safe and easy-to-use nail clippers for all pet sizes.',
      tags: ['Safety', 'Universal'],
      stock: 78,
      isNew: true,
    },
    {
      id: 'gr004',
      name: 'De-shedding Brush',
      price: 750,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 156,
      category: 'grooming',
      description: 'Reduces shedding by up to 90% with gentle bristles.',
      tags: ['De-shedding', 'Gentle'],
      stock: 3,
      isLowStock: true,
    },
  ],
  'health-care': [
    {
      id: 'hc001',
      name: 'Pet Multivitamin Supplements',
      price: 1200,
      image: 'https://images.unsplash.com/photo-1587402092301-725e37c70fd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 123,
      category: 'health-care',
      description: 'Daily multivitamin for optimal pet health and immunity.',
      tags: ['Multivitamin', 'Daily'],
      stock: 67,
      isBestSeller: true,
    },
    {
      id: 'hc002',
      name: 'Flea & Tick Prevention Collar',
      price: 850,
      image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 189,
      category: 'health-care',
      description: '8-month protection against fleas and ticks.',
      tags: ['Prevention', '8-month'],
      stock: 45,
    },
    {
      id: 'hc003',
      name: 'Digestive Health Probiotics',
      price: 1500,
      image: 'https://images.unsplash.com/photo-1552053628-0dcb5a60e3de?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 87,
      category: 'health-care',
      description: 'Supports digestive health with beneficial probiotics.',
      tags: ['Probiotics', 'Digestive'],
      stock: 34,
      isNew: true,
    },
    {
      id: 'hc004',
      name: 'Ear Cleaning Solution',
      price: 650,
      image: 'https://images.unsplash.com/photo-1605043204319-d14e5ba4719e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.4,
      reviews: 156,
      category: 'health-care',
      description: 'Gentle ear cleaning solution for regular maintenance.',
      tags: ['Gentle', 'Maintenance'],
      stock: 9,
      isLowStock: true,
    },
  ],
  'accessories': [
    {
      id: 'ac001',
      name: 'Adjustable Pet Harness',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 234,
      category: 'accessories',
      description: 'Comfortable and secure harness for daily walks.',
      tags: ['Adjustable', 'Comfortable'],
      stock: 56,
      isBestSeller: true,
    },
    {
      id: 'ac002',
      name: 'Stainless Steel Food Bowls',
      price: 750,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 189,
      category: 'accessories',
      description: 'Durable stainless steel bowls, set of 2.',
      tags: ['Stainless Steel', 'Set of 2'],
      stock: 78,
    },
    {
      id: 'ac003',
      name: 'Orthopedic Pet Bed',
      price: 2400,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 167,
      category: 'accessories',
      description: 'Memory foam pet bed for joint support and comfort.',
      tags: ['Orthopedic', 'Memory Foam'],
      stock: 23,
      isNew: true,
    },
    {
      id: 'ac004',
      name: 'Retractable Dog Leash',
      price: 650,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 145,
      category: 'accessories',
      description: '16ft retractable leash with ergonomic handle.',
      tags: ['Retractable', '16ft'],
      stock: 4,
      isLowStock: true,
    },
  ],
  'cat-toys': [
    {
      id: 'ct001',
      name: 'Interactive Feather Wand Toy',
      price: 650,
      originalPrice: 800,
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 124,
      category: 'cat-toys',
      description: 'Fun interactive wand toy to keep cats active and engaged. Features retractable design with natural feathers.',
      tags: ['Interactive', 'Feather', 'PetSafe', 'Retractable'],
      stock: 89,
      isBestSeller: true,
    },
    {
      id: 'ct002',
      name: 'Catnip Filled Mouse Toys Set',
      price: 350,
      originalPrice: 420,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 89,
      category: 'cat-toys',
      description: 'Soft mice toys filled with premium catnip. Set of 6 toys with organic catnip.',
      tags: ['Catnip', 'Mice', 'Kong', 'Set of 6'],
      stock: 67,
    },
    {
      id: 'ct003',
      name: 'Automatic Laser Pointer',
      price: 1200,
      originalPrice: 1500,
      image: 'https://images.unsplash.com/photo-1605043204319-d14e5ba4719e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 156,
      category: 'cat-toys',
      description: 'Automatic laser pointer with timer and random patterns. PetLibro brand with auto timer feature.',
      tags: ['Laser', 'Automatic', 'PetLibro', 'Timer'],
      stock: 45,
      isNew: true,
    },
    {
      id: 'ct004',
      name: 'Multi-Level Cat Tree Tower',
      price: 8500,
      originalPrice: 10000,
      image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 67,
      category: 'cat-toys',
      description: 'Large cat tree with 6 levels and sisal scratching posts. Armarkat brand quality construction.',
      tags: ['Cat Tree', '6 Levels', 'Armarkat', 'Scratching'],
      stock: 0,
      isLowStock: true,
    },
    {
      id: 'ct005',
      name: 'Cat Tunnel Play System',
      price: 1850,
      originalPrice: 2200,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 43,
      category: 'cat-toys',
      description: 'Collapsible 3-way tunnel system for cats. Pawaboo brand with easy storage.',
      tags: ['Tunnel', 'Collapsible', 'Pawaboo', '3-way'],
      stock: 23,
    },
    {
      id: 'ct006',
      name: 'Electronic Motion Fish Toy',
      price: 950,
      originalPrice: 1200,
      image: 'https://images.unsplash.com/photo-1605043204319-d14e5ba4719e?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.4,
      reviews: 92,
      category: 'cat-toys',
      description: 'Electronic fish toy with motion sensor and USB rechargeable battery. Potaroma brand quality.',
      tags: ['Electronic', 'Motion Sensor', 'Potaroma', 'USB Rechargeable'],
      stock: 34,
    },
  ],
  'cat-litter': [
    {
      id: 'cl001',
      name: 'Tidy Cats Clumping Litter',
      price: 1250,
      originalPrice: 1500,
      image: 'https://images.unsplash.com/photo-1606316321469-4d5b7d0e21c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 234,
      category: 'cat-litter',
      description: 'Premium clumping cat litter for easy cleanup. Tidy Cats brand quality with 9kg size.',
      tags: ['Clumping', 'Tidy Cats', '9kg', 'Easy Cleanup'],
      stock: 78,
      isBestSeller: true,
    },
    {
      id: 'cl002',
      name: 'Ever Clean Scented Multi-Cat',
      price: 1850,
      originalPrice: 2100,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 189,
      category: 'cat-litter',
      description: 'Scented litter designed for multi-cat households. Ever Clean brand with 10kg size.',
      tags: ['Scented', 'Multi-Cat', 'Ever Clean', '10kg'],
      stock: 56,
    },
    {
      id: 'cl003',
      name: 'Stainless Steel Litter Scoop',
      price: 450,
      originalPrice: 550,
      image: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 156,
      category: 'cat-litter',
      description: 'Durable stainless steel litter scoop for easy cleaning. iPrimio brand large size.',
      tags: ['Stainless Steel', 'Scoop', 'iPrimio', 'Large'],
      stock: 67,
    },
    {
      id: 'cl004',
      name: 'Covered Cat Litter Box Large',
      price: 2200,
      originalPrice: 2600,
      image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.5,
      reviews: 87,
      category: 'cat-litter',
      description: 'Large covered litter box for privacy and odor control. Petmate brand 64x49x38cm size.',
      tags: ['Covered', 'Large', 'Petmate', '64x49x38cm'],
      stock: 0,
      isLowStock: true,
    },
    {
      id: 'cl005',
      name: 'Washable Litter Mat',
      price: 850,
      originalPrice: 1000,
      image: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.4,
      reviews: 143,
      category: 'cat-litter',
      description: 'Washable mat to catch litter tracking. Gorilla Grip brand 76x61cm size.',
      tags: ['Washable', 'Mat', 'Gorilla Grip', '76x61cm'],
      stock: 45,
    },
    {
      id: 'cl006',
      name: 'PetSafe ScoopFree Self-Cleaning',
      price: 15000,
      originalPrice: 18000,
      image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 92,
      category: 'cat-litter',
      description: 'Automatic self-cleaning litter box system. PetSafe brand with advanced technology.',
      tags: ['Self-Cleaning', 'Automatic', 'PetSafe', 'Advanced'],
      stock: 12,
      isNew: true,
    },
  ],
  'reflex': [
    {
      id: 'rf001',
      name: 'Reflex Plus Adult Cat Food Chicken',
      price: 1850,
      originalPrice: 2100,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 267,
      category: 'reflex',
      description: 'Complete and balanced nutrition for adult cats. Reflex Plus chicken formula with 3kg weight.',
      tags: ['Adult Cat', 'Chicken', 'Reflex Plus', '3kg'],
      stock: 89,
      isBestSeller: true,
    },
    {
      id: 'rf002',
      name: 'Reflex Plus Puppy Food Lamb & Rice',
      price: 2200,
      originalPrice: 2500,
      image: 'https://images.unsplash.com/photo-1552053628-0dcb5a60e3de?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 189,
      category: 'reflex',
      description: 'High protein puppy food with lamb and rice. Reflex Plus formula with 3kg weight.',
      tags: ['Puppy', 'Lamb & Rice', 'Reflex Plus', '3kg'],
      stock: 67,
    },
    {
      id: 'rf003',
      name: 'Reflex Plus Kitten Food Salmon',
      price: 1650,
      originalPrice: 1900,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.9,
      reviews: 234,
      category: 'reflex',
      description: 'DHA enriched kitten food with salmon. Reflex Plus formula with 1.5kg weight.',
      tags: ['Kitten', 'Salmon', 'Reflex Plus', '1.5kg'],
      stock: 45,
      isNew: true,
    },
    {
      id: 'rf004',
      name: 'Reflex Plus Adult Dog Food Beef',
      price: 2450,
      originalPrice: 2800,
      image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.7,
      reviews: 156,
      category: 'reflex',
      description: 'Premium quality adult dog food with beef. Reflex Plus formula with 15kg weight.',
      tags: ['Adult Dog', 'Beef', 'Reflex Plus', '15kg'],
      stock: 0,
      isLowStock: true,
    },
    {
      id: 'rf005',
      name: 'Reflex Grain-Free Cat Food Turkey',
      price: 2800,
      originalPrice: 3200,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.8,
      reviews: 98,
      category: 'reflex',
      description: 'Grain-free cat food recipe with turkey. Reflex formula with 2kg weight.',
      tags: ['Grain-Free', 'Turkey', 'Reflex', '2kg'],
      stock: 23,
    },
    {
      id: 'rf006',
      name: 'Reflex Senior Dog Food Formula',
      price: 2600,
      originalPrice: 3000,
      image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300',
      rating: 4.6,
      reviews: 124,
      category: 'reflex',
      description: 'Joint support formula for senior dogs. Reflex formula with 12kg weight.',
      tags: ['Senior Dog', 'Joint Support', 'Reflex', '12kg'],
      stock: 34,
    },
  ],
}

export function getProductsByCategory(categoryId: string): Product[] {
  return productsData[categoryId] || []
}

export function getCategoryAnalytics(categoryId: string) {
  const products = getProductsByCategory(categoryId)
  
  if (products.length === 0) {
    return {
      lowestPriced: null,
      highestPriced: null,
      highestRated: null,
      bestSeller: null,
    }
  }

  const lowestPriced = products.reduce((min, product) => 
    product.price < min.price ? product : min
  )
  
  const highestPriced = products.reduce((max, product) => 
    product.price > max.price ? product : max
  )
  
  const highestRated = products.reduce((max, product) => 
    product.rating > max.rating ? product : max
  )
  
  const bestSeller = products.find(product => product.isBestSeller) || products[0]

  return {
    lowestPriced,
    highestPriced,
    highestRated,
    bestSeller,
  }
}